#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# Adds namespace to all resources.
#namespace: edge-sandbox-system

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
commonLabels:
  group: services
  instance: local
  project: trustbloc


apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../common
- vault-server/ingress.yml

transformers:
- sedtransform.yml
- sedb64transform.yml

vars:
- fieldref:
    fieldPath: metadata.name
  name: INGRESS_TLS_SECRET
  objref:
    apiVersion: v1
    kind: Secret
    name: wildcard-cert

secretGenerator:
- files:
  - certs/tls.crt
  - certs/tls.key
  name: wildcard-cert
  type: kubernetes.io/tls

configMapGenerator:
- behavior: merge
  envs:
  - vault-server/config.env
  name: vault-server-env
- files:
  - certs/ca.crt
  name: vault-server-ca-cert

patchesStrategicMerge:
- vault-server/add-ca.yml
