#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# Labels to add to all resources and selectors.
#commonLabels:
#  someName: someValue

# Annotations to add to all resources
#commonAnnotations:
#  someName: someValue

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  component: orb-4
  group: core
  instance: local
  project: trustbloc

replicas:
- count: 1
  name: orb-4

secretGenerator:
- files:
  - ../certs/tls.crt
  - ../certs/tls.key
  name: orb-wildcard-cert-4
  type: kubernetes.io/tls

replacements:
- source:
    kind: Service
    name: orb-4
    version: v1
  targets:
  - fieldPaths:
    - spec.tls.0.hosts.0
    - spec.rules.0.host
    options:
      delimiter: .
    select:
      kind: Ingress
      name: orb-4
  - fieldPaths:
    - spec.rules.0.http.paths.0.backend.service.name
    select:
      kind: Ingress
      name: orb-4
- source:
    kind: Secret
    name: orb-wildcard-cert-4
    version: v1
  targets:
  - fieldPaths:
    - spec.tls.0.secretName
    select:
      kind: Ingress
      name: orb-4

resources:
- ../../common/orb4
- orb/ingress.yml


transformers:
- sedtransform.yml
- sedb64transform.yml
