#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# Adds namespace to all resources.
#namespace: edge-sandbox-system

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
commonLabels:
  instance: local
  project: trustbloc


apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
- behavior: replace
  files:
  - keys/auth.key
  - keys/enc.key
  name: server-keys
- files:
  - certs/tls.crt
  - certs/tls.key
  name: wallet-server-wildcard-cert
  type: kubernetes.io/tls

configMapGenerator:
- behavior: merge
  envs:
  - config.env
  name: server-env
- files:
  - certs/ca.crt
  name: wallet-server-ca-cert

replacements:
- source:
    kind: Service
    name: wallet-support
    version: v1
  targets:
  - fieldPaths:
    - spec.tls.0.hosts.0
    - spec.rules.0.host
    options:
      delimiter: .
    select:
      kind: Ingress
      name: wallet-server
  - fieldPaths:
    - spec.rules.0.http.paths.0.backend.service.name
    select:
      kind: Ingress
      name: wallet-server
- source:
    kind: Secret
    name: wallet-server-wildcard-cert
    version: v1
  targets:
  - fieldPaths:
    - spec.tls.0.secretName
    select:
      kind: Ingress
      name: wallet-server

resources:
- ../common
- ingress.yml

transformers:
- sedtransform.yml
- sedb64transform.yml

patchesStrategicMerge:
- add-ca.yml
