---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: static-file-server
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http-port
  selector:
    app: static-file-server
status:
  loadBalancer: {}
