#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: did-method
spec:
  replicas: 1
  selector:
    matchLabels:
      app: did-method
  template:
    metadata:
      labels:
        app: did-method
    spec:
      containers:
      - name: did-method
        envFrom:
          - configMapRef:
              name: did-method-env
        image: driver-did-trustbloc:latest
        args: ["start"]
        ports:
          - containerPort: 8081
            protocol: TCP
            name: http-port
