#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# Adds namespace to all resources.
#namespace: edge-sandbox-system

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
commonLabels:
  component: wallet-web
  group: wallet
  instance: local
  project: trustbloc

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
- files:
  - certs/tls.crt
  - certs/tls.key
  name: wallet-wildcard-cert
  type: kubernetes.io/tls

replacements:
- source:
    kind: Service
    name: wallet
    version: v1
  targets:
  - fieldPaths:
    - spec.tls.0.hosts.0
    - spec.rules.0.host
    options:
      delimiter: .
    select:
      kind: Ingress
      name: wallet-web
  - fieldPaths:
    - spec.rules.0.http.paths.0.backend.service.name
    select:
      kind: Ingress
      name: wallet-web
- source:
    kind: Secret
    name: wallet-wildcard-cert
    version: v1
  targets:
  - fieldPaths:
    - spec.tls.0.secretName
    select:
      kind: Ingress
      name: wallet-web

resources:
- ../common
- ingress.yml

transformers:
- sedtransform.yml
