#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: vct
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http-port
  - name: prometheus
    port: 9100
    protocol: TCP
    targetPort: prometheus
  selector:
    app: vct
status:
  loadBalancer: {}
---
