#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# Adds namespace to all resources.
#namespace: edge-sandbox-system

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
commonLabels:
  group: services
  instance: local
  project: trustbloc


apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

vars:
- fieldref:
    fieldPath: metadata.name
  name: INGRESS_TLS_SECRET
  objref:
    apiVersion: v1
    kind: Secret
    name: vcs-wildcard-cert

configMapGenerator:
- behavior: merge
  envs:
  - issuer/config.env
  name: issuer-vcs-env
- behavior: merge
  envs:
  - verifier/config.env
  name: verifier-vcs-env
- behavior: merge
  envs:
  - holder/config.env
  name: holder-vcs-env
- behavior: merge
  envs:
  - governance/config.env
  name: governance-vcs-env
- files:
  - ../certs/ca.crt
  name: vcs-ca-cert


secretGenerator:
- files:
  - ../certs/tls.crt
  - ../certs/tls.key
  name: vcs-wildcard-cert
  type: kubernetes.io/tls

resources:
- ../../common
- issuer/ingress.yml
- verifier/ingress.yml
- holder/ingress.yml
- governance/ingress.yml

transformers:
- sedtransform.yml
- sedb64transform.yml

patchesStrategicMerge:
- issuer/add-ca.yml
- verifier/add-ca.yml
- holder/add-ca.yml
- governance/add-ca.yml
