#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# Labels to add to all resources and selectors.
#commonLabels:
#  someName: someValue

# Annotations to add to all resources
#commonAnnotations:
#  someName: someValue

generatorOptions: {}

vars:
- fieldref:
    fieldPath: metadata.name
  name: ORB_SERVICE_NAME
  objref:
    apiVersion: v1
    kind: Service
    name: orb

configMapGenerator:
- envs:
  - config.env
  name: orb-env

secretGenerator:
- envs:
  - secret.env
  name: orb-env-secret

resources:
- deployment.yml
- service.yml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: orb
  newName: ghcr.io/trustbloc-cicd/orb
  newTag: 0.1.6-snapshot-c138c96
