#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

configMapGenerator:
  - envs:
      - config.env
    name: trillian-log-server-env

secretGenerator:
  - envs:
      - secret.env
    name: trillian-log-server-env-secret

apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: trillian-log-server
  newName: ghcr.io/trustbloc-cicd/vct-log-server
  newTag: v0.1.0-snapshot-9580ec8


apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
- trillian-log-server.yml
