# 
# Copyright SecureKey Technologies Inc. All Rights Reserved. 
# 
# SPDX-License-Identifier: Apache-2.0 
# 

apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: uni-resolver-did-v1-driver
  newName: veresone/uni-resolver-did-v1-driver
  newTag: latest

vars:
- fieldref:
    fieldPath: metadata.name
  name: UNI_RESOLVER_DID_V1_DRIVER_SERVICE_NAME
  objref:
    apiVersion: v1
    kind: Service
    name: uni-resolver-did-v1-driver

apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
- deployment.yml
- service.yml
