# 
# Copyright SecureKey Technologies Inc. All Rights Reserved. 
# 
# SPDX-License-Identifier: Apache-2.0 
# 

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: uni-resolver-did-v1-driver
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http-port
  selector:
    app: uni-resolver-did-v1-driver
status:
  loadBalancer: {}
