#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  component: governance-vcs

configMapGenerator:
- envs:
  - config.env
  behavior: merge
  name: vcs-env

namePrefix: governance-

resources:
- ../../base
