#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# Labels to add to all resources and selectors.
#commonLabels:
#  someName: someValue

# Annotations to add to all resources
#commonAnnotations:
#  someName: someValue

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  component: vct-3
  group: core
  instance: local
  project: trustbloc

vars:
- fieldref:
    fieldPath: metadata.name
  name: INGRESS_TLS_SECRET
  objref:
    apiVersion: v1
    kind: Secret
    name: vct-wildcard-cert-3

configMapGenerator:
- behavior: merge
  envs:
  - vct/config.env
  name: vct-env
- files:
  - ../certs/ca.crt
  name: vct-ca-cert-3


secretGenerator:
- files:
  - ../certs/tls.crt
  - ../certs/tls.key
  name: vct-wildcard-cert-3
  type: kubernetes.io/tls

resources:
- ../../common/vct3
- vct/ingress.yml

patchesStrategicMerge:
- vct/add-ca.yml

transformers:
- sedtransform.yml
- sedb64transform.yml
