#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: orb-driver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orb-driver
  template:
    metadata:
      labels:
        app: orb-driver
    spec:
      containers:
        - name: orb-driver
          envFrom:
            - configMapRef:
                name: orb-driver-env
          image: orb-driver:latest
          args: ["start"]
          ports:
            - containerPort: 8081
              protocol: TCP
              name: http-port
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: http-port
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 5
