#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# Adds namespace to all resources.
#namespace: edge-sandbox-system

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
#namePrefix: edge-sandbox-

commonLabels:
  component: edv
  group: core
  instance: local
  project: trustbloc

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

vars:
- fieldref:
    fieldPath: metadata.name
  name: INGRESS_TLS_SECRET
  objref:
    apiVersion: v1
    kind: Secret
    name: edv-wildcard-cert

configMapGenerator:
- behavior: merge
  envs:
  - edv/config.env
  name: edv-env
- files:
  - certs/ca.crt
  name: edv-ca-cert

secretGenerator:
- files:
  - certs/tls.crt
  - certs/tls.key
  name: edv-wildcard-cert
  type: kubernetes.io/tls

transformers:
- sedtransform.yml
- sedb64transform.yml

resources:
- ../common
- edv/ingress.yml
- oathkeeper/ingress.yml

patchesStrategicMerge:
- edv/add-ca.yml
- oathkeeper/update-local-cert-store.yml
