#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
kind: Job
apiVersion: batch/v1
metadata:
  name: orb-add-followers
spec:
  template:
    spec:
      volumes:
        - name: script
          configMap:
            name: orb-add-followers-script
      restartPolicy: Never
      containers:
      - name: orb-add-followers
        image: "ubuntu:latest"
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh"]
        args: ["/opt/create_follow_activity.sh"]
        volumeMounts:
          - name: script
            mountPath: /opt
