#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# Labels to add to all resources and selectors.
#commonLabels:
#  someName: someValue

# Annotations to add to all resources
#commonAnnotations:
#  someName: someValue

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  group: core
  instance: local
  project: trustbloc

configMapGenerator:
- files:
    - ../certs/ca.crt
  name: orb-add-followers-ca-cert
- files:
    - ./create_follow_activity.sh
  name: orb-add-followers-script
- name: orb-add-followers-env
  literals:
    - ORB_MIN=||ORB_MIN||

transformers:
- sedtransform.yml

resources:
- add-followers.yml

patchesStrategicMerge:
- add-ca.yml
