# 
# Copyright SecureKey Technologies Inc. All Rights Reserved. 
# 
# SPDX-License-Identifier: Apache-2.0 
# 

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  component: rp-vcs

vars:
- fieldref:
    fieldPath: metadata.name
  name: RP_SERVICE_NAME
  objref:
    apiVersion: v1
    kind: Service
    name: vcs

configMapGenerator:
- envs:
  - config.env
  behavior: merge
  name: vcs-env

namePrefix: rp-

resources:
- ../../base
