#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: vcs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vcs
  template:
    metadata:
      labels:
        app: vcs
    spec:
      containers:
      - name: vcs
        envFrom:
          - configMapRef:
              name: vcs-env
          - secretRef:
              name: vcs-env-secret
        image: vc-server:latest
        args: ["start"]
        ports:
          - containerPort: 8081
            protocol: TCP
            name: http-port
