#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# Adds namespace to all resources.
#namespace: edge-sandbox-system

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
commonLabels:
  group: services
  project: trustbloc


apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- behavior: merge
  envs:
  - issuer/config.env
  name: issuer-vcs-env
- behavior: merge
  envs:
  - verifier/config.env
  name: verifier-vcs-env
- behavior: merge
  envs:
  - holder/config.env
  name: holder-vcs-env

secretGenerator:
- behavior: merge
  envs:
  - issuer/secret.env
  name: issuer-vcs-env-secret
- behavior: merge
  envs:
  - verifier/secret.env
  name: verifier-vcs-env-secret
- behavior: merge
  envs:
  - holder/secret.env
  name: holder-vcs-env-secret

resources:
- ../issuer
- ../verifier
- ../holder

transformers:
- sedtransform.yml
- sedb64transform.yml
