#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# Adds namespace to all resources.
#namespace: edge-sandbox-system

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
commonLabels:
  group: services
  project: trustbloc


apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- behavior: merge
  envs:
  - issuer/config.env
  name: issuer-vcs-env
- files:
  - issuer/vcs_issuer_configure.sh
  name: issuer-vcs-add-profiles-script
- behavior: merge
  envs:
  - verifier/config.env
  name: verifier-vcs-env
- files:
  - verifier/vcs_verifier_configure.sh
  name: verifier-vcs-add-profiles-script
- behavior: merge
  envs:
  - holder/config.env
  name: holder-vcs-env
- files:
  - holder/vcs_holder_configure.sh
  name: holder-vcs-add-profiles-script
- behavior: merge
  envs:
  - governance/config.env
  name: governance-vcs-env
- files:
  - governance/config.json
  name: governance-config
- files:
  - governance/vcs_governance_configure.sh
  name: governance-vcs-add-profiles-script

secretGenerator:
- behavior: merge
  envs:
  - issuer/secret.env
  name: issuer-vcs-env-secret
- behavior: merge
  envs:
  - verifier/secret.env
  name: verifier-vcs-env-secret
- behavior: merge
  envs:
  - holder/secret.env
  name: holder-vcs-env-secret
- behavior: merge
  envs:
  - governance/secret.env
  name: governance-vcs-env-secret

resources:
- ../issuer
- ../verifier
- ../holder
- ../governance
- issuer/add-profiles.yml
- verifier/add-profiles.yml
- holder/add-profiles.yml
- governance/add-profiles.yml

transformers:
- sedtransform.yml
- sedb64transform.yml

patchesStrategicMerge:
- governance/add-config.yml
