# 
# Copyright SecureKey Technologies Inc. All Rights Reserved. 
# 
# SPDX-License-Identifier: Apache-2.0 
# 

# Adds namespace to all resources.
#namespace: edge-sandbox-system

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
commonLabels:
  instance: local
  project: trustbloc


apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

vars:
- fieldref:
    fieldPath: metadata.name
  name: INGRESS_TLS_SECRET
  objref:
    apiVersion: v1
    kind: Secret
    name: wallet-wildcard-cert

secretGenerator:
- behavior: merge
  envs:
  - router/secret.env
  name: router-env-secret
- behavior: replace
  files:
  - ../keys/auth.key
  - ../keys/enc.key
  name: server-keys
- behavior: merge
  envs:
  - server/secret.env
  name: server-env-secret
- files:
  - ../certs/tls.crt
  - ../certs/tls.key
  name: wallet-wildcard-cert
  type: kubernetes.io/tls

configMapGenerator:
- behavior: merge
  envs:
  - router/config.env
  name: router-env
- behavior: merge
  envs:
  - server/config.env
  name: server-env
- behavior: merge
  envs:
  - web/config.env
  name: web-env
- files:
  - ../certs/ca.crt
  name: wallet-ca-cert

resources:
- ../../../base
- router/ingress.yml
- server/ingress.yml
- web/ingress.yml

transformers:
- sedtransform.yml
- sedb64transform.yml

patchesStrategicMerge:
- router/add-ca.yml
- server/add-ca.yml
