#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

providers:
  mockbank:
    url: https://hydra.||DOMAIN||/
    clientID: hub-auth
    clientSecret: hub-auth-secret
    name: Universal Bank
    logoURL: https://upload.wikimedia.org/wikipedia/en/a/a4/Universal_Bank.svg
