#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# Labels to add to all resources and selectors.
#commonLabels:
#  someName: someValue

# Annotations to add to all resources
#commonAnnotations:
#  someName: someValue

generatorOptions: {}

vars:
- fieldref:
    fieldPath: metadata.name
  name: WEB_SERVICE_NAME
  objref:
    apiVersion: v1
    kind: Service
    name: wallet
- fieldref:
    fieldPath: metadata.name
  name: SERVER_SERVICE_NAME
  objref:
    apiVersion: v1
    kind: Service
    name: wallet-support
- fieldref:
    fieldPath: metadata.name
  name: ROUTER_SERVICE_NAME
  objref:
    apiVersion: v1
    kind: Service
    name: router
- fieldref:
    fieldPath: metadata.name
  name: ROUTER_WS_SERVICE_NAME
  objref:
    apiVersion: v1
    kind: Service
    name: router-ws
- fieldref:
    fieldPath: metadata.name
  name: ROUTER_API_SERVICE_NAME
  objref:
    apiVersion: v1
    kind: Service
    name: router-api


configMapGenerator:
- envs:
  - web/config.env
  name: web-env
- files:
  - web/default.conf.template
  name: nginx-config-template
- envs:
  - server/config.env
  name: server-env
- envs:
  - router/config.env
  name: router-env

secretGenerator:
- envs:
  - server/secret.env
  name: server-env-secret
- literals:
  - auth.key=5QWpW+aj7WTNzEdZmTcOXXlWP78Z49CmcS9T9Bn4nx0=
  - enc.key=ccKjwMDwhXzanvKJUVSMHPGYQ9OdBqAb3Ywg7hv58qY=
  name: server-keys
- envs:
  - router/secret.env
  name: router-env-secret

resources:
- web/deployment.yml
- web/service.yml
- server/deployment.yml
- server/service.yml
- router/deployment.yml
- router/service.yml


apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: hub-router
  newName: ghcr.io/trustbloc-cicd/hub-router
  newTag: 0.1.7-snapshot-3a56649
- name: wallet-server
  newName: ghcr.io/trustbloc-cicd/wallet-server
  newTag: 0.1.7-snapshot-8649cdc
- name: wallet-web
  newName: ghcr.io/trustbloc-cicd/wallet-web
  newTag: 0.1.7-snapshot-8649cdc
