#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

apiVersion: svceng
kind: SedB64Transformer
metadata:
  name: sedb64transformer
argsOneLiner: s^||ISSUER_ADAPTER_REST_DSN||^${ISSUER_ADAPTER_REST_DSN}^ s^||RP_ADAPTER_REST_DSN||^${RP_ADAPTER_REST_DSN}^ s^||HYDRA_MYSQL_DSN||^${HYDRA_MYSQL_DSN}^ s^||ADAPTER_REST_REQUEST_TOKENS||^${ADAPTER_REST_REQUEST_TOKENS}^
