#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# Labels to add to all resources and selectors.
#commonLabels:
#  someName: someValue

# Annotations to add to all resources
#commonAnnotations:
#  someName: someValue
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  group: core
  instance: local
  project: trustbloc

vars:
- fieldref:
    fieldPath: metadata.name
  name: INGRESS_TLS_SECRET
  objref:
    apiVersion: v1
    kind: Secret
    name: orb-wildcard-cert


configMapGenerator:
- behavior: merge
  envs:
  - orb/config.env
  name: orb-env


secretGenerator:
- files:
  - certs/tls.crt
  - certs/tls.key
  name: orb-wildcard-cert
  type: kubernetes.io/tls
- behavior: merge
  envs:
  - orb/secret.env
  name: orb-env-secret

resources:
- ../orb
- orb/ingress.yml
- testnet/ingress.yml

components:
- ../../components/ipfs

transformers:
- sedtransform.yml
- sedb64transform.yml
