#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# Labels to add to all resources and selectors.
#commonLabels:
#  someName: someValue

# Annotations to add to all resources
#commonAnnotations:
#  someName: someValue
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  group: core
  instance: local
  project: trustbloc

vars:
- fieldref:
    fieldPath: metadata.name
  name: INGRESS_TLS_SECRET
  objref:
    apiVersion: v1
    kind: Secret
    name: sidetree-mock-wildcard-cert


configMapGenerator:
- behavior: merge
  envs:
  - sidetree-mock/config.env
  name: sidetree-mock-env


secretGenerator:
- files:
  - certs/tls.crt
  - certs/tls.key
  name: sidetree-mock-wildcard-cert
  type: kubernetes.io/tls

resources:
- ../sidetree-mock
- sidetree-mock/ingress.yml
- testnet/ingress.yml

transformers:
- sedtransform.yml
