#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# Adds namespace to all resources.
#namespace: edge-sandbox-system

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
commonLabels:
  component: resolver
  group: core
  instance: local
  project: trustbloc


apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

replacements:
- path: resolver/replacements.yml
  source: null
  targets: null
- path: uni-resolver-web/replacements.yml
  source: null
  targets: null
- source:
    kind: Secret
    name: resolver-wildcard-cert
    version: v1
  targets:
  - fieldPaths:
    - spec.tls.0.secretName
    select:
      kind: Ingress
      name: did-resolver
  - fieldPaths:
    - spec.tls.0.secretName
    select:
      kind: Ingress
      name: uni-resolver-web

resources:
- ../common
- resolver/ingress.yml
- uni-resolver-web/ingress.yml

transformers:
- sedtransform.yml

secretGenerator:
- files:
  - certs/tls.crt
  - certs/tls.key
  name: resolver-wildcard-cert
  type: kubernetes.io/tls

configMapGenerator:
- behavior: merge
  envs:
  - resolver/config.env
  name: did-resolver-env
- files:
  - certs/ca.crt
  name: resolver-ca-cert

patchesStrategicMerge:
- resolver/add-ca.yml
