#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# Labels to add to all resources and selectors.
#commonLabels:
#  someName: someValue

# Annotations to add to all resources
#commonAnnotations:
#  someName: someValue

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  component: orb-driver
  group: core
  project: trustbloc

configMapGenerator:
- behavior: merge
  envs:
  - config.env
  name: orb-driver-env

vars:
- fieldref:
    fieldPath: metadata.name
  name: SERVICE_NAME
  objref:
    apiVersion: v1
    kind: Service
    name: orb-driver

resources:
- ../../../base

transformers:
  - sedtransform.yml
