#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# Labels to add to all resources and selectors.
#commonLabels:
#  someName: someValue

# Annotations to add to all resources
#commonAnnotations:
#  someName: someValue

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  group: core
  instance: local
  project: trustbloc

vars:
- fieldref:
    fieldPath: metadata.name
  name: INGRESS_TLS_SECRET
  objref:
    apiVersion: v1
    kind: Secret
    name: orb-wildcard-cert

configMapGenerator:
- files:
  - ./create_follow_activity.sh
  name: orb-add-followers-script

secretGenerator:
- files:
  - ../certs/tls.crt
  - ../certs/tls.key
  name: orb-wildcard-cert
  type: kubernetes.io/tls

transformers:
- sedtransform.yml

resources:
- ingress.yml
- service.yml
- add-followers.yml
