#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

serve:
  proxy:
    port: 4455
    cors:
      enabled: true
      allowed_headers:
        - Content-Type
        - Authorization
        - Hub-Kms-Secret
        - Capability-Invocation
        - Digest
        - Signature
      allowed_origins:
        - https://wallet.||DOMAIN||
      allow_credentials: true
  api:
    port: 4456

access_rules:
  repositories:
    - file:///etc/rules/access-rules.json
  matching_strategy: glob

authenticators:
  oauth2_introspection:
    enabled: true
    config:
      introspection_url: https://hub-hydra-admin.||DOMAIN||/oauth2/introspect
  noop:
    enabled: true

authorizers:
  allow:
    enabled: true

mutators:
  header:
    enabled: true
    config:
      headers:
        HUB-KMS-USER: '{{ print .Subject }}'
  noop:
    enabled: true
