#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# Labels to add to all resources and selectors.
#commonLabels:
#  someName: someValue

# Annotations to add to all resources
#commonAnnotations:
#  someName: someValue

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  component: vct
  group: core
  instance: local
  project: trustbloc

replicas:
- count: 1
  name: vct
- count: 1
  name: trillian-log-server
- count: 1
  name: trillian-log-signer

replacements:
- source:
    kind: Service
    name: vct
    version: v1
  targets:
  - fieldPaths:
    - spec.tls.0.hosts.0
    - spec.rules.0.host
    options:
      delimiter: .
    select:
      kind: Ingress
      name: vct
- source:
    kind: Secret
    name: vct-wildcard-cert
    version: v1
  targets:
  - fieldPaths:
    - spec.tls.0.secretName
    select:
      kind: Ingress
      name: vct


configMapGenerator:
- behavior: merge
  envs:
  - vct/config.env
  name: vct-env
- files:
  - certs/ca.crt
  name: vct-ca-cert

secretGenerator:
- files:
  - certs/tls.crt
  - certs/tls.key
  name: vct-wildcard-cert
  type: kubernetes.io/tls

resources:
- ../common
- vct/ingress.yml

patchesStrategicMerge:
- vct/add-ca.yml


transformers:
- sedtransform.yml
- sedb64transform.yml
