#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# Labels to add to all resources and selectors.
#commonLabels:
#  someName: someValue

# Annotations to add to all resources
#commonAnnotations:
#  someName: someValue

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  component: vct
  group: core
  instance: local
  project: trustbloc

replicas:
  - name: vct
    count: 1

vars:
- fieldref:
    fieldPath: metadata.name
  name: INGRESS_TLS_SECRET
  objref:
    apiVersion: v1
    kind: Secret
    name: vct-wildcard-cert-1

configMapGenerator:
- behavior: merge
  envs:
  - vct/config.env
  name: vct-env
- files:
  - certs/ca.crt
  name: vct-ca-cert

secretGenerator:
- files:
  - certs/tls.crt
  - certs/tls.key
  name: vct-wildcard-cert-1
  type: kubernetes.io/tls

resources:
- ../common
- vct/ingress.yml

patchesStrategicMerge:
- vct/add-ca.yml


transformers:
- sedtransform.yml
- sedb64transform.yml
