#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# Adds namespace to all resources.
#namespace: edge-sandbox-system

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: adapter-
commonLabels:
  component: adapter
  group: services
  instance: local
  project: trustbloc


apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

vars:
- fieldref:
    fieldPath: metadata.name
  name: INGRESS_TLS_SECRET
  objref:
    apiVersion: v1
    kind: Secret
    name: adapters-wildcard-cert

secretGenerator:
- behavior: merge
  envs:
  - issuer/secret.env
  name: issuer-env-secret
- behavior: merge
  envs:
  - rp/secret.env
  name: rp-env-secret
- behavior: merge
  envs:
  - hydra/hydra-secret.env
  name: hydra-secret
- files:
  - ../certs/tls.crt
  - ../certs/tls.key
  name: adapters-wildcard-cert
  type: kubernetes.io/tls
- files:
  - ../keys/oidc-enc.key
  name: issuer-oidc-key


configMapGenerator:
- behavior: merge
  envs:
  - issuer/config.env
  name: issuer-env
- behavior: merge
  envs:
  - rp/config.env
  name: rp-env
- behavior: replace
  files:
  - rp/config.json
  name: rp-config
- files:
  - issuer/issuer_adapter_configure.sh
  name: issuer-add-profiles-config
- behavior: merge
  envs:
  - hydra/hydra-env.env
  name: hydra-env
- files:
  - ../certs/ca.crt
  name: ca-cert

resources:
- ../../../base
- issuer/ingress.yml
- rp/ingress.yml
- hydra/ingress.yml
- issuer/add-profiles.yml

transformers:
- sedtransform.yml
- sedb64transform.yml

components:
- ../../../components/hydra

patchesStrategicMerge:
- issuer/add-ca.yml
- issuer/add-key.yml
- rp/add-ca.yml
