#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: ipfs
spec:
  ports:
  - name: ipfs-port
    port: 5001
    protocol: TCP
    targetPort: ipfs-port
  selector:
    app: ipfs
status:
  loadBalancer: {}
