#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# Labels to add to all resources and selectors.
#commonLabels:
#  someName: someValue

# Annotations to add to all resources
#commonAnnotations:
#  someName: someValue

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: "-2"

replicas:
- count: 1
  name: orb

configMapGenerator:
- behavior: merge
  envs:
  - orb/config.env
  name: orb-env

secretGenerator:
- files:
  - ../certs/tls.crt
  - ../certs/tls.key
  name: orb-wildcard-cert
  type: kubernetes.io/tls
- behavior: merge
  envs:
  - orb/secret.env
  name: orb-env-secret

replacements:
- path: ../replacements-service.yml
- path: ../replacements-secret.yml

resources:
- ../../common
- ../ingress.yml


transformers:
- sedtransform.yml
- sedb64transform.yml
- labeltransformer.yml
