# 
# Copyright SecureKey Technologies Inc. All Rights Reserved. 
# 
# SPDX-License-Identifier: Apache-2.0 
# 

apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: driver-did-key
  newName: universalresolver/driver-did-key
  newTag: latest

vars:
- fieldref:
    fieldPath: metadata.name
  name: DRIVER_DID_KEY_SERVICE_NAME
  objref:
    apiVersion: v1
    kind: Service
    name: driver-did-key

apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
- deployment.yml
- service.yml
