#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mongodb-orb-kms
  name: mongodb-orb-kms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-orb-kms
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mongodb-orb-kms
    spec:
      hostname: mongodb-orb-kms
      containers:
      - image: mongo:latest
        imagePullPolicy: IfNotPresent
        ports:
          - name: mongodb-port
            protocol: TCP
            containerPort: 27017
        name: mongodb-orb-kms
        env:
        - name: MONGODB_USER
          value: 'mongoadmin'
        - name: MONGODB_PASSWORD
          value: 'secret'
        resources: {}
status: {}
