#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# Labels to add to all resources and selectors.
#commonLabels:
#  someName: someValue

# Annotations to add to all resources
#commonAnnotations:
#  someName: someValue

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  component: orb-driver
  group: core
  instance: local
  project: trustbloc

secretGenerator:
- files:
  - ../certs/tls.crt
  - ../certs/tls.key
  name: orb-driver-wildcard-cert-1
  type: kubernetes.io/tls

replacements:
- source:
    kind: Service
    name: orb-driver
    version: v1
  targets:
  - fieldPaths:
    - spec.tls.0.hosts.0
    - spec.rules.0.host
    options:
      delimiter: .
    select:
      kind: Ingress
      name: orb-driver
  - fieldPaths:
    - spec.rules.0.http.paths.0.backend.service.name
    select:
      kind: Ingress
      name: orb-driver
- source:
    kind: Secret
    name: orb-driver-wildcard-cert-1
    version: v1
  targets:
  - fieldPaths:
    - spec.tls.0.secretName
    select:
      kind: Ingress
      name: orb-driver

resources:
- ../../common/orb-driver
- ingress.yml

transformers:
- sedtransform.yml
