# 
# Copyright SecureKey Technologies Inc. All Rights Reserved. 
# 
# SPDX-License-Identifier: Apache-2.0 
# 

apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: uni-resolver-driver-did-uport
  newName: uport/uni-resolver-driver-did-uport
  newTag: 1.3.1

vars:
- fieldref:
    fieldPath: metadata.name
  name: UNI_RESOLVER_DRIVER_DID_UPORT_SERVICE_NAME
  objref:
    apiVersion: v1
    kind: Service
    name: uni-resolver-driver-did-uport

apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
- deployment.yml
- service.yml
