#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# Adds namespace to all resources.
#namespace: edge-sandbox-system

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
commonLabels:
  component: ops-kms

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../common/ops-kms
- oathkeeper/ingress.yml

transformers:
- sedtransform.yml
- sedb64transform.yml

replacements:
- path: oathkeeper/replacements.yml
  source: null
  targets: null
- source:
    kind: Secret
    name: ops-kms-wildcard-cert
    version: v1
  targets:
  - fieldPaths:
    - spec.tls.0.secretName
    select:
      kind: Ingress
      name: ops-oathkeeper-proxy

replicas:
- count: 1
  name: ops-kms

secretGenerator:
- files:
  - ../certs/tls.crt
  - ../certs/tls.key
  name: ops-kms-wildcard-cert
  type: kubernetes.io/tls
- behavior: replace
  files:
  - secret-lock.key=../keys/ops-kms-secret-lock.key
  name: ops-kms-lock-key


configMapGenerator:
- behavior: merge
  envs:
  - ../config.env
  name: ops-kms-env
- files:
  - ../certs/ca.crt
  name: ops-kms-ca-cert

patchesStrategicMerge:
- kms/add-ca.yml
- oathkeeper/update-local-cert-store.yml
