# 
# Copyright SecureKey Technologies Inc. All Rights Reserved. 
# 
# SPDX-License-Identifier: Apache-2.0 
# 

# Adds namespace to all resources.
#namespace: edge-sandbox-system

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: ops-
commonLabels:
  component: ops-kms
  group: core
  instance: local
  project: trustbloc

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../base
- oathkeeper/ingress.yml

transformers:
- sedtransform.yml
- sedb64transform.yml

components:
- ../../../components/oathkeeper

vars:
- fieldref:
    fieldPath: metadata.name
  name: INGRESS_TLS_SECRET
  objref:
    apiVersion: v1
    kind: Secret
    name: ops-kms-wildcard-cert

secretGenerator:
- files:
  - ../certs/tls.crt
  - ../certs/tls.key
  name: ops-kms-wildcard-cert
  type: kubernetes.io/tls
- behavior: merge
  envs:
  - kms/secret.env
  name: kms-env-secret
- files:
  - secret-lock.key=../keys/ops-kms-secret-lock.key
  name: kms-lock-key


configMapGenerator:
- behavior: merge
  envs:
  - kms/config.env
  name: kms-env
- behavior: replace
  files:
  - oathkeeper/config.yml
  name: oathkeeper-config
- behavior: replace
  files:
  - oathkeeper/access-rules.json
  name: oathkeeper-rules
- files:
  - ../certs/ca.crt
  name: kms-ca-cert

patchesStrategicMerge:
- kms/add-ca.yml
- kms/add-key.yml
- oathkeeper/update-local-cert-store.yml
