#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# Adds namespace to all resources.
#namespace: edge-sandbox-system

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
commonLabels:
  component: dbs
  group: third-party
  instance: local
  project: trustbloc


apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../common
- static-file-server/ingress.yml

replacements:
- source:
    kind: Service
    name: static-file-server
    version: v1
  targets:
  - fieldPaths:
    - spec.tls.0.hosts.0
    - spec.rules.0.host
    options:
      delimiter: .
    select:
      kind: Ingress
      name: static-file-server
  - fieldPaths:
    - spec.rules.0.http.paths.0.backend.service.name
    select:
      kind: Ingress
      name: static-file-server
- source:
    kind: Secret
    name: static-file-server-wildcard-cert
    version: v1
  targets:
  - fieldPaths:
    - spec.tls.0.secretName
    select:
      kind: Ingress
      name: static-file-server

secretGenerator:
- files:
  - certs/tls.crt
  - certs/tls.key
  name: static-file-server-wildcard-cert
  type: kubernetes.io/tls

transformers:
- sedtransform.yml
