# 
# Copyright SecureKey Technologies Inc. All Rights Reserved. 
# 
# SPDX-License-Identifier: Apache-2.0 
# 

# Labels to add to all resources and selectors.
#commonLabels:
#  someName: someValue

# Annotations to add to all resources
#commonAnnotations:
#  someName: someValue

generatorOptions: {}

vars:
- fieldref:
    fieldPath: metadata.name
  name: SIDETREE_MOCK_SERVICE_NAME
  objref:
    apiVersion: v1
    kind: Service
    name: sidetree-mock

configMapGenerator:
- envs:
  - config.env
  name: sidetree-mock-env

secretGenerator:
- files:
  - registry/.dockerconfigjson
  name: sidetree-mock-github-regcred
  type: kubernetes.io/dockerconfigjson

resources:
- deployment.yml
- service.yml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: sidetree-mock
  newName: ghcr.io/trustbloc/sidetree-mock
  newTag: 0.6.0
