#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: uni-registrar-web
  newName: universalregistrar/uni-registrar-web
  newTag: latest

configMapGenerator:
- files:
  - config.json
  name: uni-registrar-web-config

apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
- deployment.yml
- service.yml
