# 
# Copyright SecureKey Technologies Inc. All Rights Reserved. 
# 
# SPDX-License-Identifier: Apache-2.0 
# 

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: stakeholder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stakeholder
  template:
    metadata:
      labels:
        app: stakeholder
    spec:
      containers:
      - name: static-file-server
        envFrom:
          - configMapRef:
              name: env-stakeholder
        image: "static-file-server:latest"
        ports:
          - name: http-port
            protocol: TCP
            containerPort: 8081
