# 
# Copyright SecureKey Technologies Inc. All Rights Reserved. 
# 
# SPDX-License-Identifier: Apache-2.0 
# 

# Labels to add to all resources and selectors.
#commonLabels:
#  someName: someValue

# Annotations to add to all resources
#commonAnnotations:
#  someName: someValue

generatorOptions: {}

configMapGenerator:
- envs:
  - config.env
  name: env-stakeholder

apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
- deployment.yml
- service.yml

apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: static-file-server
  newName: halverneus/static-file-server
  newTag: v1.8.2
