#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# Labels to add to all resources and selectors.
#commonLabels:
#  someName: someValue

# Annotations to add to all resources
#commonAnnotations:
#  someName: someValue

generatorOptions: {}

configMapGenerator:
- envs:
  - csh/config.env
  name: csh-env

secretGenerator:
- envs:
  - csh/secret.env
  name: csh-env-secret

resources:
- csh/deployment.yml
- csh/service.yml


apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: hub-confidential-storage
  newName: ghcr.io/trustbloc/hub-confidential-storage
  newTag: 0.1.7
