#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: driver-did-v1
  newName: universalregistrar/driver-did-v1
  newTag: latest

apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
- deployment.yml
- service.yml
