# 
# Copyright SecureKey Technologies Inc. All Rights Reserved. 
# 
# SPDX-License-Identifier: Apache-2.0 
# 

# Adds namespace to all resources.
#namespace: edge-sandbox-system

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  component: stakeholder-one

vars:
- fieldref:
    fieldPath: metadata.name
  name: STAKEHOLDER_ONE_SERVICE_NAME
  objref:
    apiVersion: v1
    kind: Service
    name: stakeholder

nameSuffix: -one

components:
- ../../components/static-file-server

#patchesStrategicMerge:
#- some.yml
