#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

configMapGenerator:
  - envs:
      - config.env
    name: trillian-log-signer-env

secretGenerator:
  - envs:
      - secret.env
    name: trillian-log-signer-env-secret

apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: trillian-log-signer
  newName: gcr.io/trillian-opensource-ci/log_signer
  newTag: eacf01ddf6503e04cda3ee941d94820f139c7737


apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
- trillian-log-signer.yml
